# Generated by Django 5.1.7 on 2025-03-24 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI 어시스턴트')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='builder.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='웹사이트 이름')),
                ('purpose', models.TextField(verbose_name='웹사이트 목적')),
                ('target_audience', models.CharField(blank=True, max_length=200, verbose_name='대상 사용자')),
                ('design_style', models.CharField(blank=True, max_length=100, verbose_name='디자인 스타일')),
                ('features', models.JSONField(default=list, verbose_name='핵심 기능')),
                ('pages', models.JSONField(default=list, verbose_name='페이지 구성')),
                ('html_code', models.TextField(blank=True, verbose_name='HTML 코드')),
                ('css_code', models.TextField(blank=True, verbose_name='CSS 코드')),
                ('js_code', models.TextField(blank=True, verbose_name='JavaScript 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '웹사이트',
                'verbose_name_plural': '웹사이트 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='builder.website'),
        ),
    ]
